### ISSUE TITLE
 "client_id" is missing from ID token

### ISSUE THREAD

**Issue by lionick** [IdentityPython/idpy-oidc#106]
Running my tests for PR #104 , I saw that one of them failed.
It is the test_token_exchange_change_client_id_token where expects to get ID token having a "client_id" claim.
But client_id claim is not there anymore.
Is this something that you changed in purpose?
@c00kiemon5ter

**Comment by rohe** [comment]
Not changed on purpose (that I can remember) and I can't find the test you refer to.

Is it a test of your own ?

**Comment by lionick** [comment]
This is a test coming from OIDC Frontend.

**Comment by rohe** [comment]
Should be fixed by now! Can you verify that !
And if it's resolved can you accept the PR.

**Comment by lionick** [comment]
The problem is solved.
So I close this issue and will approve the PR.
