### ISSUE TITLE
Synchronize develop and main branches

### ISSUE THREAD

**Issue by ctriant** [IdentityPython/idpy-oidc#31]
Hello @rohe hope you are well,

Right now the develop branch seems to be off-sync with the main branch. Could you please schedule a fix for this issue so that we have a clean development space?

Thanks in advance

**Comment by c00kiemon5ter** [comment]
hello @rohe, @peppelinux,

It would we good to look into syncing back the branches. I think a reason this happens is that we have set `main` as the default branch, but PRs should target `develop`.
Do you think changing the default branch to be `develop` would help?

**Comment by rohe** [comment]
Yeah, we should move to the (for Idpy) normal way of doing things.
I've used the main=default while getting the idly-oidc combo in place.
Now it's time to say we're/I'm done with that and that normal operating proceedings should be in place.
Will make it happen in the next couple of days.
