### ISSUE TITLE
Official doc link is outdated

### ISSUE THREAD

**Issue by XeniaGabriela** [IdentityPython/idpy-oidc#88]
Dear Roland, 

[Official Documentation](https://idpyoidc.readthedocs.io/) results in a not found error:

![image](https://github.com/IdentityPython/idpy-oidc/assets/13744209/b08c0f09-46ad-42ba-afd0-00392aaeb020)

Kind regards,

Xenia

**Comment by c00kiemon5ter** [comment]
duplicate of #84 

fixed by #85
